# Generated by Django 4.2.2 on 2023-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_pdf_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
