# Generated by Django 4.2.2 on 2023-06-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_order_order_pdf_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recipient_email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
