# Generated by Django 4.2.2 on 2023-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_order_recipient_email_order_recipient_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_dimension",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="weight",
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
