# Generated by Django 4.2.2 on 2023-06-26 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
