# Generated by Django 4.2.2 on 2023-06-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_neighborhood_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recipient_neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.neighborhood",
            ),
        ),
    ]
