# Generated by Django 4.2.2 on 2023-06-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_business_business_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.region",
            ),
        ),
    ]
