# Generated by Django 4.2.2 on 2023-06-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_orderstatus_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default="pending",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.orderstatus",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_warehouse", "In Warehouse"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
