# Generated by Django 4.2.2 on 2023-06-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_order_status_alter_orderstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Warehouse", "In Warehouse"),
                    ("Delivered", "Delivered"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
