# Generated by Django 4.2.2 on 2023-06-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_shipment_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
